In [10]:
data.to_csv(raw_path / "market_data_raw.csv")

prices.to_csv(processed_path / "close_prices.csv")

print("Data saved successfully!")

Data saved successfully!

In [9]:
project_root = Path.cwd().parent

raw_path = project_root / "data" / "raw"
processed_path = project_root / "data" / "processed"

print(project_root)

c:\Users\admin\Desktop\QuantRisk

In [8]:
prices = data["Close"].copy()

prices.head()

Ticker            AAPL         GLD         JPM        MSFT
Date
2021-01-04  125.632523  182.330002  109.000526  207.565384
2021-01-05  127.185783  182.869995  109.593636  207.765610
2021-01-06  122.904526  179.899994  114.739685  202.378387
2021-01-07  127.098381  179.479996  118.507675  208.137497
2021-01-08  128.195435  173.339996  118.638489  209.405579

In [7]:
print("Shape:", data.shape)
print("\nColumns:")
print(data.columns)

print("\nMissing values:")
print(data.isnull().sum())

Shape: (1255, 20)

Columns:
MultiIndex([( 'Close', 'AAPL'),
            ( 'Close',  'GLD'),
            ( 'Close',  'JPM'),
            ( 'Close', 'MSFT'),
            (  'High', 'AAPL'),
            (  'High',  'GLD'),
            (  'High',  'JPM'),
            (  'High', 'MSFT'),
            (   'Low', 'AAPL'),
            (   'Low',  'GLD'),
            (   'Low',  'JPM'),
            (   'Low', 'MSFT'),
            (  'Open', 'AAPL'),
            (  'Open',  'GLD'),
            (  'Open',  'JPM'),
            (  'Open', 'MSFT'),
            ('Volume', 'AAPL'),
            ('Volume',  'GLD'),
            ('Volume',  'JPM'),
            ('Volume', 'MSFT')],
           names=['Price', 'Ticker'])

Missing values:
Price   Ticker
Close   AAPL      0
        GLD       0
        JPM       0
        MSFT      0
High    AAPL      0
        GLD       0
        JPM       0
        MSFT      0
Low     AAPL      0
        GLD       0
        JPM       0
        MSFT      0
Open    AAPL      0
        GLD       0
        JPM       0
        MSFT      0
Volume  AAPL      0
        GLD       0
        JPM       0
        MSFT      0
dtype: int64

In [6]:
test = yf.download(
    "AAPL",
    start="2025-01-01",
    end="2025-02-01"
)

print(test.head())

[*********************100%***********************]  1 of 1 completed

Price            Close        High         Low        Open    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2025-01-02  242.093140  247.305315  240.077766  247.136526  55740700
2025-01-03  241.606659  242.420743  240.147249  241.606659  40244100
2025-01-06  243.234848  245.548063  241.447813  242.549817  45045600
2025-01-07  240.464951  243.780883  239.611146  241.229392  40856000
2025-01-08  240.951416  241.954149  238.320515  240.177037  37628900

In [5]:
data = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=True
)

data.head()

[*********************100%***********************]  4 of 4 completed

Price            Close                                            High  \
Ticker            AAPL         GLD         JPM        MSFT        AAPL
Date
2021-01-04  125.632523  182.330002  109.000526  207.565384  129.709922
2021-01-05  127.185783  182.869995  109.593636  207.765610  127.894485
2021-01-06  122.904526  179.899994  114.739685  202.378387  127.224634
2021-01-07  127.098381  179.479996  118.507675  208.137497  127.787662
2021-01-08  128.195435  173.339996  118.638489  209.405579  128.758506

Price                                                  Low              \
Ticker             GLD         JPM        MSFT        AAPL         GLD
Date
2021-01-04  182.399994  110.723819  212.628417  123.059875  180.960007
2021-01-05  183.210007  110.160576  208.356784  124.681092  181.820007
2021-01-06  181.580002  115.803787  206.421193  122.690946  178.240005
2021-01-07  179.919998  120.531217  209.138665  124.127706  178.839996
2021-01-08  176.990005  118.926321  210.320936  126.428554  171.479996

Price                                     Open                          \
Ticker             JPM        MSFT        AAPL         GLD         JPM
Date
2021-01-04  108.056608  204.819326  129.622552  181.970001  110.412067
2021-01-05  107.953870  205.667933  125.127671  182.869995  109.017971
2021-01-06  111.538657  202.082808  123.991835  181.490005  113.283090
2021-01-07  117.679075  203.770522  124.613111  179.690002  118.350683
2021-01-08  116.981275  206.936042  128.564332  176.830002  118.594875

Price                      Volume
Ticker            MSFT       AAPL       GLD       JPM      MSFT
Date
2021-01-04  212.180275  143301900  14331400  16819900  37130100
2021-01-05  207.155376   97664900  12718800  13731200  23823000
2021-01-06  202.302106  155088000  18453500  24909100  35930700
2021-01-07  204.085161  109578200   7110200  21940400  27694500
2021-01-08  208.509295  105158200  24399900  12035100  22956200

In [4]:
data = yf.download(
    tickers,
    start=start_date,
    end=end_date,
    auto_adjust=True
)

data.head()

[*********************100%***********************]  4 of 4 completed

Price            Close                                            High  \
Ticker            AAPL         GLD         JPM        MSFT        AAPL
Date
2021-01-04  125.632523  182.330002  109.000526  207.565384  129.709922
2021-01-05  127.185783  182.869995  109.593636  207.765610  127.894485
2021-01-06  122.904526  179.899994  114.739685  202.378387  127.224634
2021-01-07  127.098381  179.479996  118.507675  208.137497  127.787662
2021-01-08  128.195435  173.339996  118.638489  209.405579  128.758506

Price                                                  Low              \
Ticker             GLD         JPM        MSFT        AAPL         GLD
Date
2021-01-04  182.399994  110.723819  212.628417  123.059875  180.960007
2021-01-05  183.210007  110.160576  208.356784  124.681092  181.820007
2021-01-06  181.580002  115.803787  206.421193  122.690946  178.240005
2021-01-07  179.919998  120.531217  209.138665  124.127706  178.839996
2021-01-08  176.990005  118.926321  210.320936  126.428554  171.479996

Price                                     Open                          \
Ticker             JPM        MSFT        AAPL         GLD         JPM
Date
2021-01-04  108.056608  204.819326  129.622552  181.970001  110.412067
2021-01-05  107.953870  205.667933  125.127671  182.869995  109.017971
2021-01-06  111.538657  202.082808  123.991835  181.490005  113.283090
2021-01-07  117.679075  203.770522  124.613111  179.690002  118.350683
2021-01-08  116.981275  206.936042  128.564332  176.830002  118.594875

Price                      Volume
Ticker            MSFT       AAPL       GLD       JPM      MSFT
Date
2021-01-04  212.180275  143301900  14331400  16819900  37130100
2021-01-05  207.155376   97664900  12718800  13731200  23823000
2021-01-06  202.302106  155088000  18453500  24909100  35930700
2021-01-07  204.085161  109578200   7110200  21940400  27694500
2021-01-08  208.509295  105158200  24399900  12035100  22956200

In [2]:
import pandas as pd
import yfinance as yf
from pathlib import Path
tickers = ["AAPL", "MSFT", "JPM", "GLD"]

start_date = "2021-01-01"
end_date = "2026-01-01"